// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'item': string;
  'link': string;
  'link__active': string;
  'list': string;
  'logo': string;
  'logo__link': string;
  'nav': string;
}
export const cssExports: CssExports;
export default cssExports;
