// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'link': string;
  'text__left': string;
  'text__right': string;
}
export const cssExports: CssExports;
export default cssExports;
