// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'caption': string;
  'cover': string;
  'root': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
